### ISSUE TITLE
Threadrace bug

### ISSUE THREAD

**Issue by boulik** [asgardeo/asgardeo-tomcat-saml-agent#27]
**Describe the issue:**

SSOAgentConfig is singleton, so changing this object with requests should be synchronized or use copy of object.  Concrete example of code is here:
[https://github.com/asgardio/asgardio-tomcat-saml-agent/blob/master/io.asgardio.tomcat.saml.agent/src/main/java/io/asgardio/tomcat/saml/agent/SAML2SSOAgentFilter.java#L148-L151](https://github.com/asgardio/asgardio-tomcat-saml-agent/blob/master/io.asgardio.tomcat.saml.agent/src/main/java/io/asgardio/tomcat/saml/agent/SAML2SSOAgentFilter.java#L148-L151)

After incorrect case variable ssoAgentConfig.getSAML2().isPassiveAuthn ends with value true a then all next logins will be passive.  

I made [pull request](https://github.com/asgardio/asgardio-tomcat-saml-agent/pull/25) for this bug, that includes changes after code review. 
 
**How to reproduce:**

I wrote test for this case [https://github.com/boulik/tomcat-saml-agent-stressTest](https://github.com/boulik/tomcat-saml-agent-stressTest) 
**Expected behavior:**

--

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.7.0]
 - OS: [Windows, Linux, Mac]
 - Browser: [Chrome, Firefox, Edge, Safari]
 - SDK Version: [0.1.18]
--
---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
