### ISSUE TITLE
Cross protocol SLO is not working properly for SAML 

### ISSUE THREAD

**Issue by anusharp** [asgardeo/asgardeo-tomcat-saml-agent#28]
**Describe the issue:**

Cross protocol SLO is not working properly for SAML tomact agent sample applictaion

When logout from the OIDC application which is SSO and SLO  enabled, below behavior found
1. Stay in same page when refresh is done from the SAML application for IDP initiated SSO in SAML application.
2. Prompt the Login page when refresh is done from the SAML application for SP initiated SSO in SAML application.

Logout from the SAML application is not functioning properly in both cases.

**How to reproduce:**

1.Setup  the sample SAML agent application
2. Setup OIDC Application in order to work the SSO 
( SSO & SLO enabled, IDP initialed SSO & SLO enabled with back channel logout enabled both applications) 
3. Logout from the OIDC application
4. behavior 

- Refresh the SAML application when SSO initiated by IDP, it will stay in same page without knowing back channel is logout.

- Refresh the SAML application when SSO initaied by SP itself, then it will prompt Login page  because of SAML2RequestID is null in [1] and send SSO request again to IS. This is always gives null even without logout is performed every refresh it calls the  SSO request to IS. 

Here, InResponseTo value not there in the IDP initialed SAML response while SAML response in SP initialed scenario has some value. Both case it doesn't fire /logout flow in the SAML2SSOAgentFilter instead always fire [2] condition

[1] https://github.com/asgardio/asgardio-java-saml-sdk/blob/master/io.asgardio.java.saml.sdk/src/main/java/io/asgardio/java/saml/sdk/SAML2SSOManager.java#L376
[2] https://github.com/asgardio/asgardio-tomcat-saml-agent/blob/master/io.asgardio.tomcat.saml.agent/src/main/java/io/asgardio/tomcat/saml/agent/SAML2SSOAgentFilter.java#L94
**Expected behavior:**

**Environment information** (_Please complete the following information; remove  any unnecessary fields_) **:**
 - Product Version: [IS 5.10.0]
 - OS: [Linux,]
 - Browser: [Chrome]
 - SDK Version: [io.asgardio.tomcat.saml.agent:0.1.16 ]

---

### Optional Fields

**Related issues:**

**Suggested labels:**

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
