### ISSUE TITLE
Add support for target page.

### ISSUE THREAD

**Issue by chamathns** [asgardeo/asgardeo-tomcat-saml-agent#29]
**Describe the issue:**

Currently, upon successful authentication, the SSO agent redirects the user to the page registered in the ACS URL (eg: **app/home**).

However, if a user tries to access another secured page (eg: **app/myAccount**) without having an authenticated session with the IdP, the user is first prompted for authentication. Then upon successful authentication, the user is redirected to the app/home where the user should have been redirected to the original page he tried to access; **app/myAccount**.

**Expected behaviour**

The Agent should keep track of the original page the user tried to access (**target page**), and redirect the user to the **target page** upon successful authentication.

**Comment by DonOmalVindula** [comment]
Closing the issue as this repo is no longer maintained.
